services:
  traefik:
    image: traefik:v2.10
    container_name: reverse-proxy  
    ports:
      - 80:80
      - 443:443
        #hostname: minio
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
      - /var/log:/var/log
    command:
      - --api.dashboard=true
      - --log.level=INFO
      - --accesslog=true
      - --providers.docker.network=proxy
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entryPoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls.certresolver=myresolver
      - --certificatesresolvers.myresolver.acme.email=mathieu.leclaire@iscpif.fr
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    labels:
      - traefik.enable=true
      - traefik.http.routers.mydashboard.entrypoints=websecure
      - "traefik.http.routers.mydashboard.rule=Host(`traefik.$MY_DOMAIN`)"
      - traefik.http.routers.mydashboard.service=api@internal
      - traefik.http.routers.mydashboard.middlewares=myauth   
      - traefik.http.middlewares.myauth.basicauth.users=admin:$$2y$$05$$rvvMMKOhkJKWsPE6vP7UjOqZ5/14X/RqPG0GXd2wo0q7rkxj7E.3e
  
  minio:
    image: minio/minio:RELEASE.2023-05-04T21-44-30Z
    networks:
      - proxy
    volumes:
      - /data/minio:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=miniopassword
    entrypoint: ["/bin/sh", "-c"]
    command:
      - minio server /data --console-address ":9001"
    labels:
      - traefik.enable=true
      - traefik.http.routers.myminio.entrypoints=websecure
      - "traefik.http.routers.myminio.rule=Host(`minio.$MY_DOMAIN`)"
      - traefik.http.routers.myminio.service=myminio
      - traefik.http.services.myminio.loadbalancer.server.port=9000

      - traefik.http.routers.myminioadmin.entrypoints=websecure
      - "traefik.http.routers.myminioadmin.rule=Host(`minioadmin.$MY_DOMAIN`)"
      - traefik.http.routers.myminioadmin.service=myminioadmin
      - traefik.http.services.myminioadmin.loadbalancer.server.port=9001

  mobiliscope:
    container_name: mobiliscope
    build:
      context: .
      dockerfile: apache/Dockerfile
    volumes:
      - ./logs/apache:/var/log/apache2/
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.mobiliscope.rule=Host(`ajmr.mobiliscope.com`)"
      - "traefik.http.routers.mobiliscope.tls=true"
    networks:
      - proxy
     #mobiliquest:
        #build:
        # context: .
        #dockerfile: mobiliquest/Dockerfile
        #security_opt:
        # - no-new-privileges:true
        # container_name: mobiliquest
      # ports:
      #- 8080:8081
      # volumes:
      #- 'minio_data/:/data'
      # labels:
      # - "traefik.enable=true"
      # - "traefik.docker.network.proxy"
      # - "traefik.http.routers.mobiliquest.rule=Host(`ajmr.mobiliscope.com`) && Path(`/mobiliquest`)"
      # - "traefik.http.routers.mobiliquest.tls=true"
        #- "traefik.http.services.mobiliquest.loadbalancer.server.port=8081"
        # networks:
        # - proxy

  php:
    image: php:fpm-alpine
    container_name: php
    networks:
      - internal
    volumes:
      - ./data/:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
networks:
  proxy:
    external: true
  internal:
    driver: bridge

volumes:
  letsencrypt:
    name: letsencrypt

